### ISSUE TITLE
Error for namespaced projects

### ISSUE THREAD

**Issue by XenosEleatikos** [samcontesse/gitlab-merge-request-resource#1]
### Problem
The resource doesn't work for namespaced projects.

For a namespaced project, the following error message will be displayed:

> resource script '/opt/resource/check []' failed: exit status 1
> 
> stderr:
> error retrieving opened merge requests: GET https://git.example.com/api/v4/projects/path/to/my/project/merge_requests: 404 {message: 404 Project Not Found}

### Solution
See [gitlab documentation](https://docs.gitlab.com/ce/api/README.html#namespaced-path-encoding 	 ).

> If using namespaced API calls, make sure that the NAMESPACE/PROJECT_NAME is URL-encoded.
> 
> For example, / is represented by %2F

**Comment by samcontesse** [comment]
I just saw that nested groups can be used (https://docs.gitlab.com/ee/user/group/subgroups, I was not aware of this feature). Is your project part of a sub group ? I'll make a fix to support this anyway.

**Comment by XenosEleatikos** [comment]
Hi Samuel,
Thanks for the quick reply. Yes, my project is part of a sub group. The rest of my pipeline is as defined in your readme.
Best,
Christoph

**Comment by samcontesse** [comment]
Thanks for reporting this Christoph.

The build has started on Docker Hub, the image should be ready within the next 30 minutes.

**Comment by XenosEleatikos** [comment]
Thanks for fixing and providing this package!
