### ISSUE TITLE
Trigger pipelines only if changes have occurred in specific folders on the MR.

### ISSUE THREAD

**Issue by mgsolid** [samcontesse/gitlab-merge-request-resource#16]
Trigger pipelines only if changes have occurred in specific folders on the MR.

To support the above use case, request GitlabMR to expose a param to specify 'paths' and 'ignore_paths' similar to something GIT resource offers today.

For pre-commit pipelines we would be needing this.

**Comment by samcontesse** [comment]
The API provides a list of changes per MR that could be used to filter emitted versions. I need to analyse it and check if it would fit into the check script. I'm open to PR if you have time to develop it yourself ;-)
