### ISSUE TITLE
Resource Doesn't Pick Up Latest Commits

### ISSUE THREAD

**Issue by raygervais** [samcontesse/gitlab-merge-request-resource#17]
<img width="450" alt="Screen Shot 2019-06-11 at 11 30 14 AM" src="https://user-images.githubusercontent.com/14265337/59285671-572cf000-8c3c-11e9-9771-72ca7c4bf3f4.png">

Above are four commits, yet hijacking into Concourse shows that the resource only has the latest from the original repo, not the forked one that has the commits coming in. Perhaps I implemented incorrectly? 

Below is the hijacked container, running `git log`

<img width="612" alt="Screen Shot 2019-06-11 at 11 32 26 AM" src="https://user-images.githubusercontent.com/14265337/59285840-a5da8a00-8c3c-11e9-89d1-f79671d25871.png">

If there's any other details I can provide to help, will do. Thanks for the help 👍!

**Comment by raygervais** [comment]
Update: I see that the changes are there, but without the commit message. If I wanted to preserve the message, is there such a way here?

**Comment by samcontesse** [comment]
I know nothing about your development workflow but I can imagine you work on the forked repository and you target the original repository when you create a MR. In this case, you should configure your pipeline to fetch MR from the original repository.

**Comment by raygervais** [comment]
Will do, thanks. 
Closing this issue.
