### ISSUE TITLE
Can you add a license?

### ISSUE THREAD

**Issue by kevincantu** [samcontesse/gitlab-merge-request-resource#34]
If I've just blinked and missed the file or comments someplace, forgive me, but can you add an open source license?  If you prefer a suggestion, an [MIT](https://opensource.org/licenses/MIT) or [ISC license](https://opensource.org/licenses/ISC) is always pretty flexible!

But I need to know before I fork this and give you a pull request...

**Comment by samcontesse** [comment]
An MIT licence has been added. (Sorry for the very late response)

**Comment by kevincantu** [comment]
Thanks!
