### ISSUE TITLE
merge-request-source-branch not being populated

### ISSUE THREAD

**Issue by ikegentz** [samcontesse/gitlab-merge-request-resource#50]
During the `get` step, the file `.git/merge-request-source-branch` should contain the contents of the `source_branch` key in the `.git/merge-request.json` object, but it is currently just an empty file.

**Comment by samcontesse** [comment]
Hi @ikegentz, 
I did some test with the latest version (v0.1.3) and could not reproduce this issue. Can you you update and test again? If the problem persists, please share an extract of the [GitLab API response](https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr).

**Comment by samcontesse** [comment]
Any update @ikegentz?
