### ISSUE TITLE
fail on check since v0.1.2

### ISSUE THREAD

**Issue by romain-dartigues** [samcontesse/gitlab-merge-request-resource#71]
Since release v0.1.2, I get the following error during the `check` phase against GitLab 14.9.3 and Concourse 7.7.1 (workers version 2.4):
> version is missing from previous step

Even more surprising, this error message only appear when running in a Concourse worker, executing the program locally gives me the exact same output with check version 0.1.1 and 0.1.3:
```bash
./dist/assets_linux_amd64/check <<EOF
{
  "source": {
    "uri": "https://gitlab.example.net/group/project.git",
    "sort": "asc",
    "private_token": "QlgyS8gVV0qUEKpbs1Hg"
  },
  "version": { "id": "36" }
}
EOF
[{"id":"36","updated_at":"2022-04-27T13:25:37+02:00"}]
```

fly check-resource did not help.

I did not found any obvious reason for this error to appear, but downgrading to v0.1.1 did fix.

**Comment by samcontesse** [comment]
Can you try to hijack the container and run the `check` the command to see what happens? I guess it fails gracefully (returning an empty array) but there might be something printed to the stdout that could help.

**Comment by romain-dartigues** [comment]
Will do and keep you posted.

**Comment by romain-dartigues** [comment]
Unable to reproduce :^$
