### ISSUE TITLE
Private Fork project issues , solutions?(maybe)

### ISSUE THREAD

**Issue by DrummyFloyd** [samcontesse/gitlab-merge-request-resource#73]
HI @samcontesse  , how can i pull you a merge request ? 
i've made few changements to `gitlab-merge-request-resource`  in my fork => [here](https://github.com/DrummyFloyd/gitlab-merge-request-resource)

1.  add `Drafts` params into ressource, **WIP** is no more used in gitlab since few release.

2.  add possibility to use private fork on merge request ,to do this i've made:
    - do not clone fork project , but  recreate patch file from API in this case
    - when private fork is used, , API don't provide the possibility to update BuildState because it's relative to SourceCommit, in this  case **only**, i create a note to the merge request with the
* Build URL
* Buid Name
* Build state
* gitlab Issue related

NB: i've started GO saturday, be gentle if you start reviewing my code ^^ 
-

**Comment by samcontesse** [comment]
Hi @DrummyFloyd,

Thanks for your contribution. Here is a guide on how to open a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

Is there a way to revert https://github.com/DrummyFloyd/gitlab-merge-request-resource/commit/a362ed83acc653fad29d546a5605911d2acdf25b before you submit your PR so it makes the diff easier to read?

It could also be interesting to split your changes into 2 distinct PR. The part about drafts should be pretty straightforward but I expect a little bit more work for the second one. 

Also it would be good if you can cover your changes with unit tests.

Thanks!
