### ISSUE TITLE
Question: update git?

### ISSUE THREAD

**Issue by romain-dartigues** [samcontesse/gitlab-merge-request-resource#76]
The OCI image is currently using `concourse/buildroot:git` as it's base which hasn't been updated in over five years (and I have not found the repository of these images to make a PR).
This provides git version `2.12.3` which is, as of today, 121 version behind the current `v2.36.1` (c.f.: https://github.com/git/git/tags / https://git-scm.com/downloads).

While far from being critical, it's always nice to not lag too much behind the mainstream product (and pulling your image from the Hub is quite convenient).
But this raise a few question on how would you like to address this topic (if you would).
Would you prefer to use an existing image as a base? I found:
- https://hub.docker.com/r/bitnami/git larger image (because it's Debian based) but the image tag is the git version, it help to be explicit
- https://hub.docker.com/r/rancher/gitjob smaller image but the image version does not reflect the git version
Or shall we use Alpine as a base and select the version?

Should the tag published on [Docker Hub](https://hub.docker.com/r/samcontesse/gitlab-merge-request-resource/tags) also reflect the git version from now on?

Cheers.

**Comment by samcontesse** [comment]
Hello Romain,

I fully agree that the image should provide a more recent/latest git version.

I guess we all like slim images and would therefore opt for something like Alpine. In my opinion, we should keep tagging as it is currently and simply add a note in the readme.

**Comment by romain-dartigues** [comment]
Hello Sam,

thank you for your answer.

I think the the upstream of the current `concourse/buildroot:git` image is the now deprecated https://github.com/concourse/buildroot-images repository (as it's name suggest, it's https://buildroot.org/ based).

Concourse now generate two [concourse/git-resource](https://hub.docker.com/r/concourse/git-resource) images (Alpine and Ubuntu flavoured), from https://github.com/concourse/git-resource.
My current (#82) proposition use the raw Alpine image, with just git and openssh-client (required for clones over ssh); let me know if it suit your tastes.

Regards.
